export enum TransactionType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  FUND_TRANSFER = 'FUND_TRANSFER',
  BALANCE_INQUIRY = 'BALANCE_INQUIRY',
  TRANSACTION_HISTORY = 'TRANSACTION_HISTORY'
}